kind: Application
apiVersion: flui/v1

metadata:
  name: my-sveltekit-app

build:
  strategy: dockerfile
  dockerfile: ./Dockerfile

deploy:
  port: 3000
  exposure: public
  healthcheck:
    path: /api/health
    port: 3000
  resources:
    profile: small
  scaling:
    min: 1
    max: 3
  domain:
    auto: true
    tls: true
    hostnameMode: ip
    certChallenge: http-01
    certificateProvider: lets-encrypt-staging
  env:
    - name: NODE_ENV
      value: production
